type TSortOrder = "asc" | "desc";
type TSort = "createdAt" | "answers";
type TFilter = "all" | "blocked" | "active";
type Ttransaction = "all" | "debit" | "credit" | "paid";
type Tuser = "mentor" | "mentee"|'admin';
type TscheduleType = "normal"|"recurring" ;
type Tpayment ="stripe" | "wallet";
type TquestionTab= "answered" | "unanswered"|'all';
type Tactive = "verified" | "not-verified";
type  TsortField = "createdAt" | "mostAnswered";
type TsessionTab ="upcoming" | "history";
type Tvarient = "primary" | "secondary" | "dark" | "orange";
type TalphabetOrder = "atoz" | "ztoa";
type TscheduleFilter ="all"|"today"