export {Ianswer,default as answerSchema, } from './answerModel'
export {Icategory, default as categorySchema} from './categoryModel'
export {Ichat, default as chatSchema } from './chatModel'
export {Imentee, default as menteeSchema} from './menteeModel'
export {Imentor, default as mentorSchema} from './mentorModel'
export {Imessage, TmessageType, default as messageSchema } from './messageModel'
export {Inotification, default as notificationSchema} from './notificationModel'
export {Iotp, default as otpSchema} from './otpModel'
export {Iquestion, default as questionSchema} from './questionModal'
export {IslotSchedule, default as slotScheduleSchema} from './slotScheduleModel'
export {Itime, slot, default as timeSchema} from './timeModel'
export {Itransaction, default as transactionSchema} from './transactionModel'
export {Iwallet, default as walletSchema} from './walletModel'
export {Ireview, default as reviewSchema} from './reviewModel'